name: Build and Push ARM64 Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            image: harbor.lag0.com.br/registry/alluxio
            context: ./alluxio/integration/docker
            platform: linux/arm64 #,linux/arm64

    env:
      VERSION: 2.9.4  # Define the version as a reusable variable
      ALLUXIO_BASE_URL: http://downloads.alluxio.io/downloads/files

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Harbor
      run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.lag0.com.br -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

    - name: Clone Alluxio repository
      run: git clone -b release-${{ env.VERSION }} https://github.com/Alluxio/alluxio
    
    - name: Modify Dockerfile
      run: |
        sed -i '/^FROM centos:7 as build_java8/a RUN sed -i "s|^mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-Base.repo && sed -i "s|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-Base.repo' alluxio/integration/docker/Dockerfile
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ matrix.image }}
        tags: |
          ${{ env.VERSION }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        platforms: ${{ matrix.platform }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ matrix.image }}:cache
        cache-to: type=registry,ref=${{ matrix.image }}:cache,mode=max
        build-args: |
          ALLUXIO_TARBALL=${{ env.ALLUXIO_BASE_URL }}/${{ env.VERSION }}/alluxio-${{ env.VERSION }}-bin.tar.gz