name: Build and Push ARM64 Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile_deploy
            image: registry.sinprors.org.br/boletos-ms
            context: ./
            platform: linux/amd64 #,linux/arm64
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up QEMU for cross-platform builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 2: Clone Alluxio repository
    - name: Clone Alluxio repository
      run: git clone -b release-2.9.4 https://github.com/Alluxio/alluxio

    # Step 3: Navigate to the Docker directory
    - name: Navigate to Docker directory
      run: cd ./alluxio/integration/docker

    # Step 4: Log in to Harbor registry
    - name: Log in to Harbor
      run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.lag0.com.br -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

    # Step 5: Build the Docker image for ARM64
    - name: Build Docker image for ARM64
      run: | 
        cd alluxio/integration/docker
        docker buildx build -t alluxio/alluxio:2.9.5 --platform arm64 .

    # Step 6: Tag the image
    - name: Tag Docker image
      run: docker tag alluxio/alluxio:2.9.5 harbor.lag0.com.br/registry/alluxio:2.9.5

    # Step 7: Push the image to Harbor
    - name: Push Docker image
      run: docker push harbor.lag0.com.br/registry/alluxio:2.9.5
